// This file centralizes all game balance, rendering, and configuration constants.
// It is shared between the client and server to ensure a single source of truth.

export const GAME_CONSTANTS = {
    // Game Core
    DEFAULT_MAP_WIDTH: 2000,
    DEFAULT_MAP_HEIGHT: 2000,
    DEFAULT_GAME_TIMER_MINUTES: 10,
    MAX_TOTAL_PLAYERS: 100,
    HUMAN_PLAYER_ID_PREFIX: 'human',
    AI_PLAYER_ID_PREFIX: 'ai',

    // Player & AI Defaults
    DEFAULT_SINGLE_PLAYER_AI_COUNT: 19,
    DEFAULT_MULTIPLAYER_AI_COUNT: 90,
    DEFAULT_MAP_SIZE_TERRITORIES: 200,
    INITIAL_COLONIZED_ARMY_SIZE: 1,
    INITIAL_STARTING_ARMY_SIZE: 50,

    // Probe System
    PROBE_LAUNCH_COST_FLEET: 10,
    PROBE_MIN_ARMY_TO_LAUNCH: 11, // Must have more than the cost to launch
    PROBE_UPDATE_INTERVAL_MS: 50,
    PROBE_SPEED_UNITS_PER_UPDATE: 1.25,

    // Fleet Transfer
    MIN_ARMY_TO_LEAVE_AFTER_TRANSFER: 1,
    TRANSFER_AMOUNT_DIVISOR: 2,

    // Supply Route System
    SUPPLY_ROUTE_MIN_ARMY_DIFFERENCE: 5,
    SUPPLY_ROUTE_TRANSFER_DIVISOR: 4,
    SUPPLY_ROUTE_DELAY_PER_HOP_MS: 2000,
    SUPPLY_ROUTE_LINE_WIDTH: 2,
    SUPPLY_ROUTE_ALPHA: 0.8,
    SUPPLY_ROUTE_DASH_PATTERN: [10, 10],
    SUPPLY_ROUTE_COLOR: '#00ffff',

    // Combat
    MIN_ARMY_TO_ATTACK: 2,
    ARMY_LEFT_AFTER_ATTACK: 1,
    ATTACK_POWER_BASE_MULTIPLIER: 0.8,
    ATTACK_POWER_RANDOM_RANGE: 0.4,
    DEFENSE_POWER_BASE_MULTIPLIER: 0.9,
    DEFENSE_POWER_RANDOM_RANGE: 0.2,
    ATTACKER_SURVIVAL_RATE: 0.7,
    DEFENDER_SURVIVAL_RATE: 0.8,

    // Rendering & UI
    BACKGROUND_COLOR: '#000011',
    CONNECTION_LINE_WIDTH: 1,
    CONNECTION_ALPHA: 0.3,
    CONNECTION_COLOR: '#444444',
    OWNED_CONNECTION_LINE_WIDTH: 3,
    OWNED_CONNECTION_ALPHA: 0.6,
    DRAG_PREVIEW_LINE_WIDTH: 2,
    DRAG_PREVIEW_ALPHA: 0.5,
    DRAG_PREVIEW_DASH_PATTERN: [5, 5],
    DRAG_PREVIEW_COLOR: '#ffffff',
    SHIP_ANIMATION_MIN_DURATION_MS: 500,
    SHIP_ANIMATION_SPEED_MS_PER_PX: 2,
    SHIP_ANIMATION_DEFAULT_COLOR: '#ffffff',
    TERRITORY_VISIBILITY_PADDING: 50,

    // Performance Throttling
    FPS_UPDATE_INTERVAL_MS: 1000,
    VISIBLE_TERRITORIES_UPDATE_INTERVAL_MS: 100,
    AI_UPDATE_PLAYERS_PER_FRAME_DIVISOR: 3,
    SUPPLY_ROUTE_VALIDATION_FRAME_INTERVAL: 30,
    SUPPLY_ROUTE_PROCESSING_FRAME_INTERVAL: 60,

    // Input & Controls
    DRAG_THRESHOLD_PIXELS_MOUSE: 5,
    DRAG_THRESHOLD_PIXELS_TOUCH: 10,
    DOUBLE_TAP_THRESHOLD_MS: 300,
    MOUSE_LEFT_BUTTON: 0,
    KEY_RESTART_GAME: ['r', 'R'],
    KEY_TOGGLE_MINIMAP: ['m', 'M'],

    // AI Configuration
    AI_DECISION_INTERVAL_MS: 1000,
    AI_DECISION_INTERVAL_JITTER_MS: 500,
    AI_AGGRESSION_THRESHOLD_TERRITORY_PERCENT: 0.3,
    AI_CONSOLIDATION_THRESHOLD_TERRITORY_COUNT: 5,
    AI_ATTACK_STRENGTH_MULTIPLIER: 1.5,

    // Server Specific
    SERVER_PORT: 5000,
    CORS_ORIGIN: "*",
    CORS_METHODS: ["GET", "POST"],
    ROOM_ID_GENERATION_RADIX: 36,
    ROOM_ID_GENERATION_SUBSTRING_START: 2,
    ROOM_ID_GENERATION_SUBSTRING_END: 8,
    SERVER_TICK_RATE_MS: 1000 / 20, // 20 ticks per second
};